//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace so2.modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medico
    {
        public Medico()
        {
            this.Reserva = new HashSet<Reserva>();
        }
    
        public int id_medico { get; set; }
        public string nombre_medico { get; set; }
        public string telefono_medico { get; set; }
    
        public virtual ICollection<Reserva> Reserva { get; set; }
    }
}
